### ISSUE TITLE
Deployment guide feedback - replace PMSA with PSA

### ISSUE THREAD

**Issue by shashivj** [aws-ia/cfn-abi-aws-reference-guide#87]
Section heading: ABI Timelines, Week 2. There is no specific role in AWS called as PMSA.
Documentation issue description: so Please replace it with PSA.

https://w.amazon.com/bin/view/AWSBuiltIn-Onboarding

**Comment by kkvinjam** [comment]
Done.

**Comment by shashivj** [comment]
Thanks
